# Group Channels

API for Channels

## /api/channels/
### GET
Gets a list of all channels
+ Response 200

            {
                "foo": "bar"
            }

## /api/channels/items/

### GET

+ Response 200

            {
                "bat": "baz"
            }
